export const TEST_ACTION = 'TEST_ACTION'
export const ON_LOGIN = 'ON_LOGIN'
export const ON_SIGNUP = 'ON_SIGNUP'
export const ON_LOAD = 'ON_LOAD'
export const ON_CHANGE_PASSWORD = 'ON_CHANGE_PASSWORD'