export const TEST_ACTION = 'TEST_ACTION'
export const ON_LOGIN = 'ON_LOGIN'
export const ON_SIGNUP = 'ON_SIGNUP'
export const ON_LOAD = 'ON_LOAD'
export const ON_CHANGE_PASSWORD = 'ON_CHANGE_PASSWORD'
export const ON_AVATAR_CHANGE = 'ON_AVATAR_CHANGE'
export const ON_PROFILE_CHANGE = 'ON_PROFILE_CHANGE'
export const ON_LOGOUT = 'ON_LOGOUT'